dataset_path: /hdd1/dataset/ffhq_thumbs # path containing dataset

adam_lr_g: 0.001 # 'lr in Adam optimizer'
adam_lr_d: 0.001 # 'lr in Adam optimizer'
adam_beta1: 0.0 # 'beta1 in Adam optimizer'
adam_beta2: 0.99 # 'beta2 in Adam optimizer'
lambda_gp: 10.0 #'Lambda GP'

size_starting_epochs: 5,15,25,35,40
batchsize: 16,16,16,8,4
growing_epochs: 5,5,5,1,1
iteration: 40
#
start_rotation: 2000
start_occlusion_aware: 2000
#
#
ch: 256 # '#Channels'
out_res: 128
#
## architecture
architecture: pggan # stylegan, pggan, deepvoxels
rgb: True # rgb or rgbd
use_cuda: True
rotate_conv_input: False
lambda_depth: 10
depth_min: 1.0
lambda_geometric: 3

## camera parameter prior
## rotation angle range (+-radian)
x_rotate: 0.3054
y_rotate: 1.0472
z_rotate: 0
# translation range
x_translate: 0
y_translate: 0
z_translate: 0

# test angles
test_x_rotate: 0
test_y_rotate: 0.7854
test_z_rotate: 0
test_x_translate: 0
test_y_translate: 0
test_z_translate: 0

## hps (device)
enable_cuda_profiling: False # 'Whether to enable CUDA profiling.'
#
#
## hps (I/O)
out: '/nas/users/sangil/projects/rgbdgan_pytorch' # 'Directory to output the result'
auto_resume_dir: '' # 'Directory for loading the saved models'

#
snapshot_interval: 10000 # 'Interval of snapshot'
evaluation_sample_interval: 500 # 'Interval of evaluation sampling'
display_interval: 100 # 'Interval of displaying log to console'
get_model_from_interation: '' # 'Load this iteration (it is a string)'
#
## Style GAN
style_mixing_rate: 0.0 # ' Style Mixing Prob'
enable_blur: False # 'Enable blur function after upscaling/downscaling'

