dataset_path: /hdd1/dataset/ffhq_thumbs # path containing dataset

adam_lr_g: 0.0001 # 'lr in Adam optimizer'
adam_lr_d: 0.0003 # 'lr in Adam optimizer'
adam_beta1: 0.0 # 'beta1 in Adam optimizer'
adam_beta2: 0.999 # 'beta2 in Adam optimizer'
lambda_gp: 1. # 'lambda for gradient penalty'

## schedule
### 8, 16, 32, 64, 128
size_starting_epochs: -1,-1,-1,50,200 # if not use, set starting epochs to -1
batchsize: 32,32,32,16,4
growing_epochs: 5,5,5,5,5
iteration: 130

#
#
ch: 256 # '#Channels'
in_res: 32 # 8, 16, 32, 64, 128
out_res: 64 # 8, 16, 32, 64, 128 (bigger than in_res)
#
## architecture
architecture: pggan # stylegan, pggan, deepvoxels
res_dis: False
use_cuda: True
rgbd: True # rgb or rgbd
osgan: False
# rotate_conv_input: False
lambda_depth: 10
depth_min: 1.0
lambda_geometric: 3

## starting rotation (if rgbd: True)
start_rotation: 2
start_occlusion_aware: 2

## evaluation metric
fid: True

## camera parameter prior
## rotation angle range (+-radian)
x_rotate: 0.3054
y_rotate: 1.0472
z_rotate: 0
# translation range
x_translate: 0
y_translate: 0
z_translate: 0

# test angles
test_x_rotate: 0
test_y_rotate: 1.0472
test_z_rotate: 0
test_x_translate: 0
test_y_translate: 0
test_z_translate: 0

## Style GAN
style_mixing_rate: 0.0 # ' Style Mixing Prob'
enable_blur: False # 'Enable blur function after upscaling/downscaling'

